#!/usr/bin/perl

use strict;
use utf8;

use Encode::Locale;
binmode(STDIN, ":encoding(locale)") || die;
binmode(STDOUT, ":encoding(locale)") || die;
use Data::Dump;

while (<STDIN>) {
    dd $_;
    s/-/—/g;
    dd $_;
    print;
}
